package main

// sections is the registry of every component documentation page, in the same
// order as the shadcn/ui docs sidebar. Descriptions mirror the shadcn/ui docs
// (tech-specific mentions adapted to this Go + Templ + Alpine.js port). Each
// example's Func names the templ function whose source is shown as the code
// sample.
var sections = []Section{
	{Slug: "accordion", Title: "Accordion", Description: "A vertically stacked set of interactive headings that each reveal a section of content.", Examples: []Example{{Func: "AccordionDemo", Component: AccordionDemo()}}},
	{Slug: "alert", Title: "Alert", Description: "Displays a callout for user attention.", Examples: []Example{{Name: "Default", Func: "AlertDemo", Component: AlertDemo()}, {Name: "Destructive", Func: "AlertDestructive", Component: AlertDestructive()}}},
	{Slug: "alert-dialog", Title: "Alert Dialog", Description: "A modal dialog that interrupts the user with important content and expects a response.", Examples: []Example{{Func: "AlertDialogDemo", Component: AlertDialogDemo()}}},
	{Slug: "aspect-ratio", Title: "Aspect Ratio", Description: "Displays content within a desired ratio.", Examples: []Example{{Func: "AspectRatioDemo", Component: AspectRatioDemo()}}},
	{Slug: "avatar", Title: "Avatar", Description: "An image element with a fallback for representing the user.", Examples: []Example{{Func: "AvatarDemo", Component: AvatarDemo()}}},
	{Slug: "badge", Title: "Badge", Description: "Displays a badge or a component that looks like a badge.", Examples: []Example{{Func: "BadgeDemo", Component: BadgeDemo()}}},
	{Slug: "breadcrumb", Title: "Breadcrumb", Description: "Displays the path to the current resource using a hierarchy of links.", Examples: []Example{{Func: "BreadcrumbDemo", Component: BreadcrumbDemo()}}},
	{Slug: "button", Title: "Button", Description: "Displays a button or a component that looks like a button.", Examples: []Example{{Name: "Default", Func: "ButtonDemo", Component: ButtonDemo()}, {Name: "Variants", Func: "ButtonVariants", Component: ButtonVariants()}, {Name: "Sizes", Func: "ButtonSizes", Component: ButtonSizes()}, {Name: "With icon", Func: "ButtonWithIcon", Component: ButtonWithIcon()}, {Name: "Loading", Func: "ButtonLoading", Component: ButtonLoading()}}},
	{Slug: "button-group", Title: "Button Group", Description: "A container that groups related buttons together with consistent styling.", Examples: []Example{{Func: "ButtonGroupDemo", Component: ButtonGroupDemo()}}},
	{Slug: "calendar", Title: "Calendar", Description: "A calendar component that allows users to select a date or a range of dates.", Examples: []Example{{Func: "CalendarDemo", Component: CalendarDemo()}}},
	{Slug: "card", Title: "Card", Description: "Displays a card with header, content, and footer.", Examples: []Example{{Func: "CardDemo", Component: CardDemo()}}},
	{Slug: "carousel", Title: "Carousel", Description: "A carousel with motion and swipe built using Alpine.js.", Examples: []Example{{Func: "CarouselDemo", Component: CarouselDemo()}}},
	{Slug: "chart", Title: "Chart", Description: "Beautiful charts powered by Chart.js, themed with your CSS variables.", Examples: []Example{{Func: "ChartDemo", Component: ChartDemo()}}},
	{Slug: "checkbox", Title: "Checkbox", Description: "A control that allows the user to toggle between checked and not checked.", Examples: []Example{{Func: "CheckboxDemo", Component: CheckboxDemo()}}},
	{Slug: "collapsible", Title: "Collapsible", Description: "An interactive component which expands/collapses a panel.", Examples: []Example{{Func: "CollapsibleDemo", Component: CollapsibleDemo()}}},
	{Slug: "combobox", Title: "Combobox", Description: "Autocomplete input with a list of suggestions.", Examples: []Example{{Func: "ComboboxDemo", Component: ComboboxDemo()}}},
	{Slug: "command", Title: "Command", Description: "Command menu for search and quick actions.", Examples: []Example{{Func: "CommandDemo", Component: CommandDemo()}}},
	{Slug: "context-menu", Title: "Context Menu", Description: "Displays a menu of actions triggered by a right click.", Examples: []Example{{Func: "ContextMenuDemo", Component: ContextMenuDemo()}}},
	{Slug: "data-table", Title: "Data Table", Description: "Powerful table and datagrids with filter, sort, pagination and row selection.", Examples: []Example{{Func: "DataTableDemo", Component: DataTableDemo()}}},
	{Slug: "date-picker", Title: "Date Picker", Description: "A date picker component with range and presets.", Examples: []Example{{Func: "DatePickerDemo", Component: DatePickerDemo()}}},
	{Slug: "dialog", Title: "Dialog", Description: "A window overlaid on either the primary window or another dialog window, rendering the content underneath inert.", Examples: []Example{{Func: "DialogDemo", Component: DialogDemo()}}},
	{Slug: "direction", Title: "Direction", Description: "A provider component that sets the text direction for your application.", Examples: []Example{{Func: "DirectionDemo", Component: DirectionDemo()}}},
	{Slug: "drawer", Title: "Drawer", Description: "A drawer component that slides in from the edge of the screen.", Examples: []Example{{Func: "DrawerDemo", Component: DrawerDemo()}}},
	{Slug: "dropdown-menu", Title: "Dropdown Menu", Description: "Displays a menu to the user — such as a set of actions or functions — triggered by a button.", Examples: []Example{{Func: "DropdownMenuDemo", Component: DropdownMenuDemo()}}},
	{Slug: "empty", Title: "Empty", Description: "Use the Empty component to display an empty state.", Examples: []Example{{Func: "EmptyDemo", Component: EmptyDemo()}}},
	{Slug: "field", Title: "Field", Description: "Combine labels, controls, and help text to compose accessible form fields and grouped inputs.", Examples: []Example{{Func: "FieldDemo", Component: FieldDemo()}}},
	{Slug: "hover-card", Title: "Hover Card", Description: "For sighted users to preview content available behind a link.", Examples: []Example{{Func: "HoverCardDemo", Component: HoverCardDemo()}}},
	{Slug: "input", Title: "Input", Description: "A text input component for forms and user data entry with built-in styling and accessibility features.", Examples: []Example{{Func: "InputDemo", Component: InputDemo()}}},
	{Slug: "input-group", Title: "Input Group", Description: "Add addons, buttons, and helper content to inputs.", Examples: []Example{{Func: "InputGroupDemo", Component: InputGroupDemo()}}},
	{Slug: "input-otp", Title: "Input OTP", Description: "Accessible one-time password component with copy-paste functionality.", Examples: []Example{{Func: "InputOTPDemo", Component: InputOTPDemo()}}},
	{Slug: "item", Title: "Item", Description: "A versatile component for displaying content with media, title, description, and actions.", Examples: []Example{{Func: "ItemDemo", Component: ItemDemo()}}},
	{Slug: "kbd", Title: "Kbd", Description: "Used to display textual user input from keyboard.", Examples: []Example{{Func: "KbdDemo", Component: KbdDemo()}}},
	{Slug: "label", Title: "Label", Description: "Renders an accessible label associated with controls.", Examples: []Example{{Func: "LabelDemo", Component: LabelDemo()}}},
	{Slug: "menubar", Title: "Menubar", Description: "A visually persistent menu common in desktop applications that provides quick access to a consistent set of commands.", Examples: []Example{{Func: "MenubarDemo", Component: MenubarDemo()}}},
	{Slug: "native-select", Title: "Native Select", Description: "A styled native HTML select element with consistent design system integration.", Examples: []Example{{Func: "NativeSelectDemo", Component: NativeSelectDemo()}}},
	{Slug: "navigation-menu", Title: "Navigation Menu", Description: "A collection of links for navigating websites.", Examples: []Example{{Func: "NavigationMenuDemo", Component: NavigationMenuDemo()}}},
	{Slug: "pagination", Title: "Pagination", Description: "Pagination with page navigation, next and previous links.", Examples: []Example{{Func: "PaginationDemo", Component: PaginationDemo()}}},
	{Slug: "popover", Title: "Popover", Description: "Displays rich content in a portal, triggered by a button.", Examples: []Example{{Func: "PopoverDemo", Component: PopoverDemo()}}},
	{Slug: "progress", Title: "Progress", Description: "Displays an indicator showing the completion progress of a task, typically displayed as a progress bar.", Examples: []Example{{Func: "ProgressDemo", Component: ProgressDemo()}}},
	{Slug: "radio-group", Title: "Radio Group", Description: "A set of checkable buttons — known as radio buttons — where no more than one of the buttons can be checked at a time.", Examples: []Example{{Func: "RadioGroupDemo", Component: RadioGroupDemo()}}},
	{Slug: "resizable", Title: "Resizable", Description: "Accessible resizable panel groups and layouts with keyboard support.", Examples: []Example{{Func: "ResizableDemo", Component: ResizableDemo()}}},
	{Slug: "scroll-area", Title: "Scroll Area", Description: "Augments native scroll functionality for custom, cross-browser styling.", Examples: []Example{{Func: "ScrollAreaDemo", Component: ScrollAreaDemo()}}},
	{Slug: "select", Title: "Select", Description: "Displays a list of options for the user to pick from — triggered by a button.", Examples: []Example{{Func: "SelectDemo", Component: SelectDemo()}}},
	{Slug: "separator", Title: "Separator", Description: "Visually or semantically separates content.", Examples: []Example{{Func: "SeparatorDemo", Component: SeparatorDemo()}}},
	{Slug: "sheet", Title: "Sheet", Description: "Extends the Dialog component to display content that complements the main content of the screen.", Examples: []Example{{Func: "SheetDemo", Component: SheetDemo()}}},
	{Slug: "sidebar", Title: "Sidebar", Description: "A composable, themeable and customizable sidebar component.", Examples: []Example{{Func: "SidebarDemo", Component: SidebarDemo()}}},
	{Slug: "skeleton", Title: "Skeleton", Description: "Use to show a placeholder while content is loading.", Examples: []Example{{Func: "SkeletonDemo", Component: SkeletonDemo()}}},
	{Slug: "slider", Title: "Slider", Description: "An input where the user selects a value from within a given range.", Examples: []Example{{Func: "SliderDemo", Component: SliderDemo()}}},
	{Slug: "sonner", Title: "Sonner", Description: "An opinionated toast component.", Examples: []Example{{Func: "SonnerDemo", Component: SonnerDemo()}}},
	{Slug: "spinner", Title: "Spinner", Description: "An indicator that can be used to show a loading state.", Examples: []Example{{Func: "SpinnerDemo", Component: SpinnerDemo()}}},
	{Slug: "switch", Title: "Switch", Description: "A control that allows the user to toggle between checked and not checked.", Examples: []Example{{Func: "SwitchDemo", Component: SwitchDemo()}}},
	{Slug: "table", Title: "Table", Description: "A responsive table component.", Examples: []Example{{Func: "TableDemo", Component: TableDemo()}}},
	{Slug: "tabs", Title: "Tabs", Description: "A set of layered sections of content — known as tab panels — that are displayed one at a time.", Examples: []Example{{Func: "TabsDemo", Component: TabsDemo()}}},
	{Slug: "textarea", Title: "Textarea", Description: "Displays a form textarea or a component that looks like a textarea.", Examples: []Example{{Func: "TextareaDemo", Component: TextareaDemo()}}},
	{Slug: "toast", Title: "Toast", Description: "A succinct message that is displayed temporarily.", Examples: []Example{{Func: "ToastDemo", Component: ToastDemo()}}},
	{Slug: "toggle", Title: "Toggle", Description: "A two-state button that can be either on or off.", Examples: []Example{{Func: "ToggleDemo", Component: ToggleDemo()}}},
	{Slug: "toggle-group", Title: "Toggle Group", Description: "A set of two-state buttons that can be toggled on or off.", Examples: []Example{{Func: "ToggleGroupDemo", Component: ToggleGroupDemo()}}},
	{Slug: "tooltip", Title: "Tooltip", Description: "A popup that displays information related to an element when the element receives keyboard focus or the mouse hovers over it.", Examples: []Example{{Func: "TooltipDemo", Component: TooltipDemo()}}},
	{Slug: "typography", Title: "Typography", Description: "Styles for headings, paragraphs, lists, etc.", Examples: []Example{{Func: "TypographyDemo", Component: TypographyDemo()}}},
}
