// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
package ui

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/davidbudnick/shadcn-templ/internal/twmerge"

// Sonner — a toast notification system backed by an Alpine store.
// Place @ui.Sonner("", nil) once in the page (e.g. in layout).
// Trigger a toast from any element:
//   x-on:click="$store.sonner.add({ message: 'Hello!', type: 'default' })"
// Supported types: default | success | error | info | warning

// SonnerToaster is the fixed container that renders active toasts.
// It registers the Alpine store and auto-dismisses toasts after 4 s.
func SonnerToaster(classes string, attrs templ.Attributes) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{twmerge.Merge("fixed bottom-4 right-4 z-[100] flex flex-col gap-2 w-full max-w-sm pointer-events-none", classes)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div x-data x-init=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(`
  if (!Alpine.store('sonner')) {
    Alpine.store('sonner', {
      toasts: [],
      nextId: 1,
      add(toast) {
        const id = this.nextId++;
        this.toasts.push({ id, message: toast.message || '', type: toast.type || 'default', title: toast.title || '' });
        setTimeout(() => this.remove(id), 4000);
      },
      remove(id) { this.toasts = this.toasts.filter(t => t.id !== id); }
    });
  }`)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/sonner.templ`, Line: 28, Col: 4}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var4 string
		templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/sonner.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, attrs)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "><template x-for=\"toast in $store.sonner.toasts\" :key=\"toast.id\"><div class=\"pointer-events-auto flex w-full items-start gap-3 rounded-xl border bg-background p-4 shadow-lg transition-all\" :class=\"{\n\t\t\t\t\t'border-green-500/30 bg-green-50 dark:bg-green-950/20': toast.type === 'success',\n\t\t\t\t\t'border-red-500/30 bg-red-50 dark:bg-red-950/20': toast.type === 'error',\n\t\t\t\t\t'border-blue-500/30 bg-blue-50 dark:bg-blue-950/20': toast.type === 'info',\n\t\t\t\t\t'border-yellow-500/30 bg-yellow-50 dark:bg-yellow-950/20': toast.type === 'warning'\n\t\t\t\t}\" x-transition:enter=\"transition ease-out duration-300\" x-transition:enter-start=\"opacity-0 translate-y-2\" x-transition:enter-end=\"opacity-100 translate-y-0\" x-transition:leave=\"transition ease-in duration-150\" x-transition:leave-start=\"opacity-100 translate-y-0\" x-transition:leave-end=\"opacity-0 translate-y-2\"><div class=\"flex-1 min-w-0\"><p class=\"text-sm font-semibold\" x-show=\"toast.title\" x-text=\"toast.title\"></p><p class=\"text-sm text-muted-foreground\" x-text=\"toast.message\"></p></div><button type=\"button\" class=\"shrink-0 rounded-sm opacity-70 hover:opacity-100 focus:outline-none\" x-on:click=\"$store.sonner.remove(toast.id)\" aria-label=\"Dismiss\"><svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\"><path d=\"M18 6 6 18\"></path><path d=\"m6 6 12 12\"></path></svg></button></div></template></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
